/*
Copyright 2026 Red Hat, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package podplacement – Handle() admission path tests.
//
// These tests exercise the complete Handle() → decode → gate → patch pipeline,
// which the existing webhook_cel_test.go does not cover (it calls
// applyCELInWebhook directly).
//
// Design note on the test client:
// Handle() calls a.client.List() to fetch PodPlacementConfigs.  When that call
// errors out (e.g. nil client dereference), the webhook is intentionally
// designed to "fail open": it empties the PPC list and continues processing.
// For tests that only need to verify the gate/decode/patch plumbing we use a
// nil kubernetes.Clientset (clientSet is used only for the async event goroutine
// which is safe to no-op) and a minimally wired scheme.  Tests that need PPCs
// to be matched go through applyCELInWebhook directly (already covered in
// webhook_cel_test.go).
package podplacement

import (
	"context"
	"encoding/json"
	"fmt"
	"sync"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"

	jsonpatch "gomodules.xyz/jsonpatch/v2"
	admissionv1 "k8s.io/api/admission/v1"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	clientgoscheme "k8s.io/client-go/kubernetes/scheme"
	"k8s.io/client-go/tools/record"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/client/fake"
	"sigs.k8s.io/controller-runtime/pkg/webhook/admission"

	"github.com/panjf2000/ants/v2"

	"github.com/openshift/multiarch-tuning-operator/api/common/plugins"
	"github.com/openshift/multiarch-tuning-operator/api/v1beta1"
	. "github.com/openshift/multiarch-tuning-operator/pkg/testing/builder"
	"github.com/openshift/multiarch-tuning-operator/pkg/utils"
)

// buildHandleRequest encodes a Pod as a raw CREATE admission.Request.
func buildHandleRequest(pod *corev1.Pod) admission.Request {
	raw, err := json.Marshal(pod)
	Expect(err).NotTo(HaveOccurred(), "failed to marshal pod")
	return admission.Request{
		AdmissionRequest: admissionv1.AdmissionRequest{
			UID:       "test-uid",
			Operation: admissionv1.Create,
			Object:    runtime.RawExtension{Raw: raw},
			Resource:  metav1.GroupVersionResource{Group: "", Version: "v1", Resource: "pods"},
		},
	}
}

// newHandleWebhook returns a webhook wired with a fake controller-runtime
// client (empty store) so that client.List returns an empty PPC list without
// hitting a real API server.  The scheme is populated so that
// admission.NewDecoder can decode Pods.
func newHandleWebhook() *PodSchedulingGateMutatingWebHook {
	s := runtime.NewScheme()
	Expect(clientgoscheme.AddToScheme(s)).To(Succeed(), "add core scheme")
	Expect(v1beta1.AddToScheme(s)).To(Succeed(), "add multiarch scheme")
	fakeClient := fake.NewClientBuilder().WithScheme(s).Build()
	pool, err := ants.NewMultiPool(1, 1, ants.LeastTasks, ants.WithNonblocking(true))
	Expect(err).NotTo(HaveOccurred(), "ants pool")
	// clientSet nil is safe: delayedSchedulingGatedEvent skips the goroutine when
	// clientSet is nil (informational-only path, not required for admission logic).
	// apiReader nil is safe: the webhook falls back to the informer-backed client only when apiReader != nil.
	return NewPodSchedulingGateMutatingWebHook(fakeClient, nil, nil, nil, s, record.NewFakeRecorder(32), pool)
}

// ── helpers ───────────────────────────────────────────────────────────────────

// applyJSONPatches applies a slice of JSON Patch operations to srcJSON using
// a simple loop (no library needed for the patch ops produced by the webhook).
func applyJSONPatches(srcJSON []byte, patches []jsonpatch.JsonPatchOperation) ([]byte, error) {
	var obj map[string]interface{}
	if err := json.Unmarshal(srcJSON, &obj); err != nil {
		return nil, err
	}
	for _, p := range patches {
		applyJSONPatchOp(obj, p)
	}
	return json.Marshal(obj)
}

// applyJSONPatchOp applies a single RFC 6902 JSON Patch operation to the
// provided map. Only "add" and "replace" operations on simple "/" paths are
// handled — sufficient for the patches generated by this webhook.
func applyJSONPatchOp(obj map[string]interface{}, op jsonpatch.JsonPatchOperation) {
	if op.Path == "" {
		return
	}
	parts := splitJSONPointer(op.Path)
	if len(parts) == 0 {
		return
	}
	switch op.Operation {
	case "add", "replace":
		setNestedValue(obj, parts, op.Value)
	}
}

func splitJSONPointer(path string) []string {
	if len(path) > 0 && path[0] == '/' {
		path = path[1:]
	}
	if path == "" {
		return nil
	}
	var out []string
	start := 0
	for i := 0; i < len(path); i++ {
		if path[i] == '/' {
			out = append(out, unescapeJSONPointerToken(path[start:i]))
			start = i + 1
		}
	}
	out = append(out, unescapeJSONPointerToken(path[start:]))
	return out
}

func unescapeJSONPointerToken(s string) string {
	out := make([]byte, 0, len(s))
	for i := 0; i < len(s); i++ {
		if s[i] == '~' && i+1 < len(s) {
			switch s[i+1] {
			case '0':
				out = append(out, '~')
				i++
				continue
			case '1':
				out = append(out, '/')
				i++
				continue
			}
		}
		out = append(out, s[i])
	}
	return string(out)
}

func escapeJSONPointer(s string) string {
	result := make([]byte, 0, len(s))
	for i := 0; i < len(s); i++ {
		switch s[i] {
		case '~':
			result = append(result, '~', '0')
		case '/':
			result = append(result, '~', '1')
		default:
			result = append(result, s[i])
		}
	}
	return string(result)
}

func setNestedValue(obj map[string]interface{}, parts []string, value interface{}) {
	if len(parts) == 1 {
		obj[parts[0]] = value
		return
	}
	next, ok := obj[parts[0]]
	if !ok {
		child := map[string]interface{}{}
		obj[parts[0]] = child
		setNestedValue(child, parts[1:], value)
		return
	}
	if child, ok2 := next.(map[string]interface{}); ok2 {
		setNestedValue(child, parts[1:], value)
	}
}

// buildTestPPCWithCELRule builds a minimal PodPlacementConfig with a single
// CEL rule.
func buildTestPPCWithCELRule(name, ns string, priority uint8, fallback, expression, arch string) v1beta1.PodPlacementConfig {
	return *NewPodPlacementConfig().WithName(name).WithNamespace(ns).WithPriority(priority).
		WithCelArchitecturePlacement(true, []string{fallback}, []plugins.ArchitectureRule{
			NewRule("rule", expression, arch),
		}).Build()
}

// mockReader implements client.Reader for use as a spy in tests.
type mockReader struct {
	listFn func() error
}

func (m *mockReader) Get(_ context.Context, _ client.ObjectKey, _ client.Object, _ ...client.GetOption) error {
	return nil
}

func (m *mockReader) List(_ context.Context, _ client.ObjectList, _ ...client.ListOption) error {
	if m.listFn != nil {
		return m.listFn()
	}
	return nil
}

var _ = Describe("CEL Webhook", func() {

	Context("Handle admission", func() {

		// TestHandleAdmission_ResponseAllowed
		It("should return Allowed=true for a plain pod", func() {
			pod := NewPod().WithName("plain-pod").WithNamespace("test-wh").WithContainersImages("nginx:latest").Build()
			wh := newHandleWebhook()
			resp := wh.Handle(context.Background(), buildHandleRequest(pod))
			Expect(resp.Allowed).To(BeTrue(), "expected Allowed=true, got: %v", resp.Result)
		})

		// TestHandleAdmission_SchedulingGatePatchPresent
		It("should include a patch that adds /spec/schedulingGates", func() {
			pod := NewPod().WithName("plain-pod").WithNamespace("test-wh").WithContainersImages("nginx:latest").Build()
			wh := newHandleWebhook()
			resp := wh.Handle(context.Background(), buildHandleRequest(pod))
			Expect(resp.Allowed).To(BeTrue(), "expected Allowed=true, got: %v", resp.Result)

			gateFound := false
			for _, p := range resp.Patches {
				if p.Path == "/spec/schedulingGates" && p.Operation == "add" {
					gateFound = true
				}
			}
			Expect(gateFound).To(BeTrue(),
				"expected patch to add /spec/schedulingGates; patches=%v", resp.Patches)
		})

		// TestHandleAdmission_SchedulingGateLabelPatchPresent
		It("should include the scheduling gate label in the patch", func() {
			pod := NewPod().WithName("plain-pod").WithNamespace("test-wh").WithContainersImages("nginx:latest").Build()
			wh := newHandleWebhook()
			resp := wh.Handle(context.Background(), buildHandleRequest(pod))
			Expect(resp.Allowed).To(BeTrue(), "expected Allowed=true, got: %v", resp.Result)

			originalJSON, _ := json.Marshal(pod)
			patchedJSON, err := applyJSONPatches(originalJSON, resp.Patches)
			if err != nil {
				// Fallback: inspect labels directly via the patch values.
				for _, p := range resp.Patches {
					if p.Path == "/metadata/labels" || p.Path == "/metadata/labels/"+escapeJSONPointer(utils.SchedulingGateLabel) {
						return // Label patch found, test passes
					}
				}
				Fail("could not apply patches: " + err.Error())
				return
			}

			var patched corev1.Pod
			Expect(json.Unmarshal(patchedJSON, &patched)).To(Succeed(), "unmarshal patched pod")
			Expect(patched.Labels[utils.SchedulingGateLabel]).To(Equal(utils.SchedulingGateLabelValueGated),
				"label %q = %q, want %q — all labels: %v",
				utils.SchedulingGateLabel, patched.Labels[utils.SchedulingGateLabel],
				utils.SchedulingGateLabelValueGated, patched.Labels)
		})

		// TestHandleAdmission_PodWithNodeName_GateNotAdded
		It("should not add the scheduling gate to pods already bound to a node (NodeName set)", func() {
			pod := NewPod().WithName("bound-pod").WithNamespace("test-wh").WithNodeName("worker-1").WithContainersImages("nginx:latest").Build()
			wh := newHandleWebhook()
			resp := wh.Handle(context.Background(), buildHandleRequest(pod))
			Expect(resp.Allowed).To(BeTrue(), "expected Allowed=true for already-bound pod")
			for _, p := range resp.Patches {
				Expect(p.Path == "/spec/schedulingGates" && p.Operation == "add").To(BeFalse(),
					"should not add scheduling gate to pod with NodeName set; patch=%v", p)
			}
		})

		// TestHandleAdmission_BadRawInput_ReturnsBadRequest
		It("should return Allowed=false when the raw object bytes cannot be decoded as a Pod", func() {
			wh := newHandleWebhook()
			resp := wh.Handle(context.Background(), admission.Request{
				AdmissionRequest: admissionv1.AdmissionRequest{
					UID:       "bad-uid",
					Operation: admissionv1.Create,
					Object:    runtime.RawExtension{Raw: []byte(`{invalid json`)},
					Resource:  metav1.GroupVersionResource{Group: "", Version: "v1", Resource: "pods"},
				},
			})
			Expect(resp.Allowed).To(BeFalse(), "expected Allowed=false for malformed raw input")
		})

		// TestHandleAdmission_AlreadyGatedPod_NoDuplicateGate
		It("should not add a duplicate scheduling gate when the pod already carries it", func() {
			pod := NewPod().WithName("pre-gated").WithNamespace("test-wh").WithSchedulingGates(utils.SchedulingGateName).WithContainersImages("nginx:latest").Build()
			wh := newHandleWebhook()
			resp := wh.Handle(context.Background(), buildHandleRequest(pod))
			Expect(resp.Allowed).To(BeTrue(), "expected Allowed=true")

			originalJSON, _ := json.Marshal(pod)
			patchedJSON, err := applyJSONPatches(originalJSON, resp.Patches)
			if err != nil {
				addGateOps := 0
				for _, p := range resp.Patches {
					if p.Path == "/spec/schedulingGates" && p.Operation == "add" {
						addGateOps++
					}
				}
				Expect(addGateOps).To(BeNumerically("<=", 1),
					"expected at most 1 add-schedulingGates patch, got %d", addGateOps)
				return
			}

			var patched corev1.Pod
			Expect(json.Unmarshal(patchedJSON, &patched)).To(Succeed(), "unmarshal patched pod")

			count := 0
			for _, g := range patched.Spec.SchedulingGates {
				if g.Name == utils.SchedulingGateName {
					count++
				}
			}
			Expect(count).To(BeNumerically("<=", 1),
				"expected exactly 1 scheduling gate in patched pod, got %d — gates=%v",
				count, patched.Spec.SchedulingGates)
		})

		// TestHandleAdmission_CELAppliedViaApplyCELInWebhook
		It("should apply CEL architecture constraints and add the scheduling gate in the correct order", func() {
			ctx := context.Background()
			recorder := record.NewFakeRecorder(8)

			raw := NewPod().WithName("my-pod").WithNamespace("test-wh").WithLabels("app", "myapp").WithContainersImages("nginx:latest").Build()
			pod := newPod(raw, ctx, recorder)

			ppc := buildTestPPCWithCELRule("cel-ppc", "default", 100,
				utils.ArchitectureAmd64,
				`self.metadata.name == "my-pod"`,
				utils.ArchitecturePpc64le)

			wh := &PodSchedulingGateMutatingWebHook{}
			wh.applyCELInWebhook(ctx, pod, []v1beta1.PodPlacementConfig{ppc})
			pod.ensureSchedulingGate()

			Expect(pod.Spec.Affinity).NotTo(BeNil())
			Expect(pod.Spec.Affinity.NodeAffinity).NotTo(BeNil())
			Expect(pod.Spec.Affinity.NodeAffinity.RequiredDuringSchedulingIgnoredDuringExecution).NotTo(BeNil())
			archFound := false
			for _, term := range pod.Spec.Affinity.NodeAffinity.RequiredDuringSchedulingIgnoredDuringExecution.NodeSelectorTerms {
				for _, expr := range term.MatchExpressions {
					if expr.Key == utils.ArchLabel && len(expr.Values) == 1 && expr.Values[0] == utils.ArchitecturePpc64le {
						archFound = true
					}
				}
			}
			Expect(archFound).To(BeTrue(), "expected ppc64le architecture constraint, not found")
			Expect(pod.HasSchedulingGate()).To(BeTrue(),
				"expected scheduling gate to be present after ensureSchedulingGate")
		})
	})

	Context("apiReader and ppcCacheSynced behavior", func() {

		// TestHandle_CacheSynced_NoPPC_NoAPIReaderFallback
		It("should NOT call apiReader when informer cache is synced and returns no PPCs", func() {
			s := runtime.NewScheme()
			Expect(clientgoscheme.AddToScheme(s)).To(Succeed())
			Expect(v1beta1.AddToScheme(s)).To(Succeed())

			fakeClient := fake.NewClientBuilder().WithScheme(s).Build()
			pool, err := ants.NewMultiPool(1, 1, ants.LeastTasks, ants.WithNonblocking(true))
			Expect(err).NotTo(HaveOccurred())

			apiReaderCalled := false
			var mockAPIReader mockReader
			mockAPIReader.listFn = func() error {
				apiReaderCalled = true
				return nil
			}

			cacheSynced := func() bool { return true }
			wh := NewPodSchedulingGateMutatingWebHook(fakeClient, &mockAPIReader, cacheSynced, nil, s, record.NewFakeRecorder(32), pool)

			pod := NewPod().WithName("plain-pod").WithNamespace("test-wh").WithContainersImages("nginx:latest").Build()
			_ = wh.Handle(context.Background(), buildHandleRequest(pod))

			Expect(apiReaderCalled).To(BeFalse(),
				"apiReader should NOT be called when informer cache is synced and returned no PPCs")
		})

		// TestHandle_CacheNotSynced_NoPPC_APIReaderFallbackAllowed
		It("should call apiReader when informer cache is NOT yet synced", func() {
			s := runtime.NewScheme()
			Expect(clientgoscheme.AddToScheme(s)).To(Succeed())
			Expect(v1beta1.AddToScheme(s)).To(Succeed())

			fakeClient := fake.NewClientBuilder().WithScheme(s).Build()
			pool, err := ants.NewMultiPool(1, 1, ants.LeastTasks, ants.WithNonblocking(true))
			Expect(err).NotTo(HaveOccurred())

			apiReaderCalled := false
			var mockAPIReader mockReader
			mockAPIReader.listFn = func() error {
				apiReaderCalled = true
				return nil
			}

			cacheSynced := func() bool { return false }
			wh := NewPodSchedulingGateMutatingWebHook(fakeClient, &mockAPIReader, cacheSynced, nil, s, record.NewFakeRecorder(32), pool)

			pod := NewPod().WithName("plain-pod").WithNamespace("test-wh").WithContainersImages("nginx:latest").Build()
			_ = wh.Handle(context.Background(), buildHandleRequest(pod))

			Expect(apiReaderCalled).To(BeTrue(),
				"apiReader SHOULD be called when informer cache is not yet synced and returned no PPCs")
		})

		// TestHandle_NilCacheSynced_NoPPC_APIReaderFallbackAllowed
		It("should call apiReader when ppcCacheSynced is nil (no informer wired)", func() {
			s := runtime.NewScheme()
			Expect(clientgoscheme.AddToScheme(s)).To(Succeed())
			Expect(v1beta1.AddToScheme(s)).To(Succeed())

			fakeClient := fake.NewClientBuilder().WithScheme(s).Build()
			pool, err := ants.NewMultiPool(1, 1, ants.LeastTasks, ants.WithNonblocking(true))
			Expect(err).NotTo(HaveOccurred())

			apiReaderCalled := false
			var mockAPIReader mockReader
			mockAPIReader.listFn = func() error {
				apiReaderCalled = true
				return nil
			}

			wh := NewPodSchedulingGateMutatingWebHook(fakeClient, &mockAPIReader, nil, nil, s, record.NewFakeRecorder(32), pool)

			pod := NewPod().WithName("plain-pod").WithNamespace("test-wh").WithContainersImages("nginx:latest").Build()
			_ = wh.Handle(context.Background(), buildHandleRequest(pod))

			Expect(apiReaderCalled).To(BeTrue(),
				"apiReader SHOULD be called when ppcCacheSynced is nil (no informer wired)")
		})

		// TestHandle_ApiReaderNil_NoFallback
		It("should not panic and return Allowed=true when apiReader is nil", func() {
			pod := NewPod().WithName("plain-pod").WithNamespace("test-wh").WithContainersImages("nginx:latest").Build()
			wh := newHandleWebhook()
			resp := wh.Handle(context.Background(), buildHandleRequest(pod))
			Expect(resp.Allowed).To(BeTrue(), "expected Allowed=true with nil apiReader, got: %v", resp.Result)
		})
	})

	Context("applyCELInWebhook", func() {

		// TestApplyCELInWebhook_AppliesArchitecturesBeforePersistence
		Describe("applies architecture constraints from the matching PPC", func() {
			var (
				ctx      context.Context
				recorder *record.FakeRecorder
			)

			BeforeEach(func() {
				ctx = context.Background()
				recorder = record.NewFakeRecorder(10)
			})

			DescribeTable("should apply (or skip) architectures based on PPC configuration",
				func(
					pod *corev1.Pod,
					matchingPPCs []v1beta1.PodPlacementConfig,
					expectedArchitectures []string,
					expectModified bool,
				) {
					webhook := &PodSchedulingGateMutatingWebHook{}
					podWrapper := newPod(pod, ctx, recorder)
					webhook.applyCELInWebhook(ctx, podWrapper, matchingPPCs)

					if expectModified {
						Expect(podWrapper.Spec.Affinity).NotTo(BeNil(), "Expected node affinity to be set")
						Expect(podWrapper.Spec.Affinity.NodeAffinity).NotTo(BeNil())
						Expect(podWrapper.Spec.Affinity.NodeAffinity.RequiredDuringSchedulingIgnoredDuringExecution).NotTo(BeNil())

						found := false
						for _, term := range podWrapper.Spec.Affinity.NodeAffinity.RequiredDuringSchedulingIgnoredDuringExecution.NodeSelectorTerms {
							for _, expr := range term.MatchExpressions {
								if expr.Key == utils.ArchLabel && expr.Operator == corev1.NodeSelectorOpIn {
									found = true
									Expect(expr.Values).To(HaveLen(len(expectedArchitectures)))
									for i, arch := range expectedArchitectures {
										Expect(expr.Values[i]).To(Equal(arch))
									}
								}
							}
						}
						Expect(found).To(BeTrue(), "Architecture requirement not found in node affinity")
					} else {
						if podWrapper.Spec.Affinity != nil &&
							podWrapper.Spec.Affinity.NodeAffinity != nil &&
							podWrapper.Spec.Affinity.NodeAffinity.RequiredDuringSchedulingIgnoredDuringExecution != nil {
							for _, term := range podWrapper.Spec.Affinity.NodeAffinity.RequiredDuringSchedulingIgnoredDuringExecution.NodeSelectorTerms {
								for _, expr := range term.MatchExpressions {
									Expect(expr.Key).NotTo(Equal(utils.ArchLabel), "Unexpected architecture requirement found")
								}
							}
						}
					}
				},
				Entry("applies CEL architecture from highest priority PPC",
					NewPod().WithName("test-pod").WithNamespace("default").Build(),
					[]v1beta1.PodPlacementConfig{
						*NewPodPlacementConfig().WithName("ppc-high-priority").WithNamespace("default").WithPriority(100).
							WithCelArchitecturePlacement(true, []string{"amd64"}, []plugins.ArchitectureRule{
								NewRule("test-rule", "self.metadata.name == 'test-pod'", "ppc64le"),
							}).Build(),
					},
					[]string{"ppc64le"}, true,
				),
				Entry("no modification when no CEL plugin enabled",
					NewPod().WithName("test-pod").WithNamespace("default").Build(),
					[]v1beta1.PodPlacementConfig{
						*NewPodPlacementConfig().WithName("ppc-no-cel").WithNamespace("default").WithPriority(100).
							WithNodeAffinityScoring(true).Build(),
					},
					nil, false,
				),
				Entry("applies fallback when no rules match",
					NewPod().WithName("other-pod").WithNamespace("default").Build(),
					[]v1beta1.PodPlacementConfig{
						*NewPodPlacementConfig().WithName("ppc-with-fallback").WithNamespace("default").WithPriority(100).
							WithCelArchitecturePlacement(true, []string{"amd64", "arm64"}, []plugins.ArchitectureRule{
								NewRule("test-rule", "self.metadata.name == 'test-pod'", "ppc64le"),
							}).Build(),
					},
					[]string{"amd64", "arm64"}, true,
				),
			)
		})

		// TestApplyCELInWebhook_MalformedPPCDoesNotBlockLowerPriority
		It("should not block lower-priority PPCs when the higher-priority PPC has malformed CEL", func() {
			ctx := context.Background()
			recorder := record.NewFakeRecorder(10)

			pod := NewPod().WithName("test-pod").WithNamespace("default").Build()
			matchingPPCs := []v1beta1.PodPlacementConfig{
				*NewPodPlacementConfig().WithName("ppc-malformed-high-priority").WithNamespace("default").WithPriority(200).
					WithCelArchitecturePlacement(true, []string{"amd64"}, []plugins.ArchitectureRule{
						NewRule("malformed-rule", "self.metadata.name ==", "s390x"),
					}).Build(),
				*NewPodPlacementConfig().WithName("ppc-valid-low-priority").WithNamespace("default").WithPriority(100).
					WithCelArchitecturePlacement(true, []string{"amd64"}, []plugins.ArchitectureRule{
						NewRule("valid-rule", "self.metadata.name == 'test-pod'", "ppc64le"),
					}).Build(),
			}

			webhook := &PodSchedulingGateMutatingWebHook{}
			podWrapper := newPod(pod, ctx, recorder)
			webhook.applyCELInWebhook(ctx, podWrapper, matchingPPCs)

			Expect(podWrapper.Spec.Affinity).NotTo(BeNil(), "Expected node affinity to be set from lower-priority PPC")
			Expect(podWrapper.Spec.Affinity.NodeAffinity).NotTo(BeNil())
			Expect(podWrapper.Spec.Affinity.NodeAffinity.RequiredDuringSchedulingIgnoredDuringExecution).NotTo(BeNil())

			found := false
			for _, term := range podWrapper.Spec.Affinity.NodeAffinity.RequiredDuringSchedulingIgnoredDuringExecution.NodeSelectorTerms {
				for _, expr := range term.MatchExpressions {
					if expr.Key == utils.ArchLabel && expr.Operator == corev1.NodeSelectorOpIn {
						found = true
						Expect(expr.Values).To(ConsistOf("ppc64le"))
					}
				}
			}
			Expect(found).To(BeTrue(), "Architecture requirement from lower-priority PPC not found")
		})

		// TestApplyCELInWebhook_RespectsPPCPriority
		It("should sort PPCs by priority and apply only the highest-priority matching PPC", func() {
			ctx := context.Background()
			recorder := record.NewFakeRecorder(10)

			pod := NewPod().WithName("test-pod").WithNamespace("default").Build()
			matchingPPCs := []v1beta1.PodPlacementConfig{
				*NewPodPlacementConfig().WithName("ppc-low-priority").WithNamespace("default").WithPriority(50).
					WithCelArchitecturePlacement(true, []string{"arm64"}, nil).Build(),
				*NewPodPlacementConfig().WithName("ppc-high-priority").WithNamespace("default").WithPriority(150).
					WithCelArchitecturePlacement(true, []string{"ppc64le"}, nil).Build(),
				*NewPodPlacementConfig().WithName("ppc-medium-priority").WithNamespace("default").WithPriority(100).
					WithCelArchitecturePlacement(true, []string{"s390x"}, nil).Build(),
			}

			webhook := &PodSchedulingGateMutatingWebHook{}
			podWrapper := newPod(pod, ctx, recorder)
			webhook.applyCELInWebhook(ctx, podWrapper, matchingPPCs)

			Expect(podWrapper.Spec.Affinity).NotTo(BeNil())
			Expect(podWrapper.Spec.Affinity.NodeAffinity).NotTo(BeNil())
			Expect(podWrapper.Spec.Affinity.NodeAffinity.RequiredDuringSchedulingIgnoredDuringExecution).NotTo(BeNil())

			found := false
			for _, term := range podWrapper.Spec.Affinity.NodeAffinity.RequiredDuringSchedulingIgnoredDuringExecution.NodeSelectorTerms {
				for _, expr := range term.MatchExpressions {
					if expr.Key == utils.ArchLabel && expr.Operator == corev1.NodeSelectorOpIn {
						found = true
						Expect(expr.Values).To(ConsistOf("ppc64le"),
							"Expected architecture [ppc64le] from highest priority PPC, got %v", expr.Values)
					}
				}
			}
			Expect(found).To(BeTrue(), "Architecture requirement from highest priority PPC not found")
		})

		// TestApplyCELInWebhook_RemovesNodeSelectorArchBeforeAdmission
		It("should remove kubernetes.io/arch from nodeSelector and set NodeAffinity before admission", func() {
			ctx := context.Background()
			recorder := record.NewFakeRecorder(10)

			pod := NewPod().WithName("test-pod-with-nodeselector").WithNamespace("default").
				WithNodeSelectors(utils.ArchLabel, "amd64", "other-key", "other-value").Build()

			matchingPPCs := []v1beta1.PodPlacementConfig{
				*NewPodPlacementConfig().WithName("ppc-cel").WithNamespace("default").WithPriority(100).
					WithCelArchitecturePlacement(true, []string{"ppc64le"}, nil).Build(),
			}

			webhook := &PodSchedulingGateMutatingWebHook{}
			podWrapper := newPod(pod, ctx, recorder)
			webhook.applyCELInWebhook(ctx, podWrapper, matchingPPCs)

			Expect(podWrapper.Spec.NodeSelector).NotTo(HaveKey(utils.ArchLabel),
				"kubernetes.io/arch should have been removed from nodeSelector by the webhook")
			Expect(podWrapper.Spec.NodeSelector["other-key"]).To(Equal("other-value"),
				"non-arch nodeSelector key must be preserved")

			Expect(podWrapper.Spec.Affinity).NotTo(BeNil())
			Expect(podWrapper.Spec.Affinity.NodeAffinity).NotTo(BeNil())
			Expect(podWrapper.Spec.Affinity.NodeAffinity.RequiredDuringSchedulingIgnoredDuringExecution).NotTo(BeNil())
			terms := podWrapper.Spec.Affinity.NodeAffinity.RequiredDuringSchedulingIgnoredDuringExecution.NodeSelectorTerms
			Expect(terms).NotTo(BeEmpty(), "Expected at least one NodeSelectorTerm after applyCELInWebhook")

			found := false
			for _, term := range terms {
				for _, expr := range term.MatchExpressions {
					if expr.Key == utils.ArchLabel && expr.Operator == corev1.NodeSelectorOpIn {
						found = true
						Expect(expr.Values).To(ConsistOf("ppc64le"))
					}
				}
			}
			Expect(found).To(BeTrue(), "Architecture requirement not found in NodeAffinity after applyCELInWebhook")
		})

		// TestApplyCELInWebhook_ControllerIdempotencyAfterWebhookMutation
		It("should not change NodeSelectorTerms count when re-applying the same constraints (KEP-3838 idempotency)", func() {
			ctx := context.Background()
			recorder := record.NewFakeRecorder(10)

			pod := NewPod().WithName("post-webhook-pod").WithNamespace("default").
				WithNodeSelectorTermsMatchExpressions(
					[]corev1.NodeSelectorRequirement{
						{Key: "topology.kubernetes.io/zone", Operator: corev1.NodeSelectorOpIn, Values: []string{"us-east-1a"}},
						{Key: utils.ArchLabel, Operator: corev1.NodeSelectorOpIn, Values: []string{"ppc64le"}},
					},
				).Build()

			matchingPPCs := []v1beta1.PodPlacementConfig{
				*NewPodPlacementConfig().WithName("ppc-cel").WithNamespace("default").WithPriority(100).
					WithCelArchitecturePlacement(true, []string{"ppc64le"}, nil).Build(),
			}

			originalTermCount := len(pod.Spec.Affinity.NodeAffinity.RequiredDuringSchedulingIgnoredDuringExecution.NodeSelectorTerms)

			webhook := &PodSchedulingGateMutatingWebHook{}
			podWrapper := newPod(pod, ctx, recorder)
			webhook.applyCELInWebhook(ctx, podWrapper, matchingPPCs)

			finalTermCount := len(podWrapper.Spec.Affinity.NodeAffinity.RequiredDuringSchedulingIgnoredDuringExecution.NodeSelectorTerms)
			Expect(finalTermCount).To(Equal(originalTermCount),
				"NodeSelectorTerms count changed from %d to %d — "+
					"this would cause Kubernetes to reject the controller update with HTTP 422 "+
					"(KEP-3838 immutability constraint)", originalTermCount, finalTermCount)

			zoneFound := false
			for _, term := range podWrapper.Spec.Affinity.NodeAffinity.RequiredDuringSchedulingIgnoredDuringExecution.NodeSelectorTerms {
				for _, expr := range term.MatchExpressions {
					if expr.Key == "topology.kubernetes.io/zone" {
						zoneFound = true
					}
				}
			}
			Expect(zoneFound).To(BeTrue(), "non-architecture zone constraint was removed — must be preserved")

			archFound := false
			for _, term := range podWrapper.Spec.Affinity.NodeAffinity.RequiredDuringSchedulingIgnoredDuringExecution.NodeSelectorTerms {
				for _, expr := range term.MatchExpressions {
					if expr.Key == utils.ArchLabel {
						archFound = true
						Expect(expr.Values).To(ConsistOf("ppc64le"))
					}
				}
			}
			Expect(archFound).To(BeTrue(), "Architecture constraint not found after controller re-application")
		})

		// TestApplyCELInWebhook_KEP3838_ArchOnlyTermPreserved
		// Regression test for the root cause of the integration failure:
		// a 2-term pod (arch-only term + zone term) must keep both terms after the
		// webhook fires so the controller's subsequent Update does not send fewer
		// terms than what was persisted, which would be rejected with HTTP 422
		// ("no additions/deletions to non-empty NodeSelectorTerms list are allowed",
		// KEP-3838 immutability requirement).
		It("should preserve both NodeSelectorTerms when one term is arch-only (KEP-3838 webhook regression)", func() {
			ctx := context.Background()
			recorder := record.NewFakeRecorder(10)

			// Pod with 2 terms: Term 1 = arch-only, Term 2 = zone-only.
			// This mirrors the exact scenario from the failing integration test.
			pod := NewPod().WithName("kep3838-webhook-pod").WithNamespace("default").
				WithNodeSelectorTermsMatchExpressions(
					// Term 1: arch-only — must NOT be dropped
					[]corev1.NodeSelectorRequirement{
						{Key: utils.ArchLabel, Operator: corev1.NodeSelectorOpIn, Values: []string{utils.ArchitectureAmd64}},
					},
					// Term 2: zone constraint — must be preserved
					[]corev1.NodeSelectorRequirement{
						{Key: "topology.kubernetes.io/zone", Operator: corev1.NodeSelectorOpIn, Values: []string{"us-east-1a"}},
					},
				).Build()

			matchingPPCs := []v1beta1.PodPlacementConfig{
				*NewPodPlacementConfig().WithName("kep3838-ppc").WithNamespace("default").WithPriority(100).
					WithCelArchitecturePlacement(true, []string{utils.ArchitecturePpc64le}, []plugins.ArchitectureRule{
						NewRule("always-true", `true`, utils.ArchitecturePpc64le),
					}).Build(),
			}

			wh := &PodSchedulingGateMutatingWebHook{}
			podWrapper := newPod(pod, ctx, recorder)
			wh.applyCELInWebhook(ctx, podWrapper, matchingPPCs)

			terms := podWrapper.Spec.Affinity.NodeAffinity.RequiredDuringSchedulingIgnoredDuringExecution.NodeSelectorTerms
			Expect(terms).To(HaveLen(2),
				"webhook must NOT shrink NodeSelectorTerms (KEP-3838): expected 2 terms, got %d — "+
					"this would cause a Kubernetes HTTP 422 on the controller Update", len(terms))

			// Verify architecture was updated to ppc64le in BOTH terms
			for i, term := range terms {
				found := false
				for _, expr := range term.MatchExpressions {
					if expr.Key == utils.ArchLabel {
						found = true
						Expect(expr.Values).To(ConsistOf(utils.ArchitecturePpc64le),
							"term[%d]: expected ppc64le architecture, got %v", i, expr.Values)
					}
				}
				Expect(found).To(BeTrue(), "term[%d]: architecture constraint missing after webhook applied", i)
			}

			// Verify zone is preserved in term 1 (index 1 = original zone-only term)
			zoneFound := false
			for _, expr := range terms[1].MatchExpressions {
				if expr.Key == "topology.kubernetes.io/zone" {
					zoneFound = true
					Expect(expr.Values).To(ConsistOf("us-east-1a"), "zone value was modified")
				}
			}
			Expect(zoneFound).To(BeTrue(), "zone constraint was removed from the zone term — must be preserved")
		})

		It("should match pods by generateName in CEL expressions", func() {
			ctx := context.Background()
			recorder := record.NewFakeRecorder(8)

			pod := NewPod().WithGenerateName("myapp-").WithNamespace("default").Build()
			ppcs := []v1beta1.PodPlacementConfig{
				*NewPodPlacementConfig().
					WithName("generatename-ppc").
					WithNamespace("default").
					WithPriority(100).
					WithCelArchitecturePlacement(true, []string{utils.ArchitectureAmd64},
						[]plugins.ArchitectureRule{
							NewRule("match-generatename", "self.metadata.generateName.startsWith('myapp')", utils.ArchitecturePpc64le),
						}).
					Build(),
			}

			wh := &PodSchedulingGateMutatingWebHook{}
			wrappedPod := newPod(pod, ctx, recorder)
			wh.applyCELInWebhook(ctx, wrappedPod, ppcs)

			archs := extractArchitectures(pod)
			Expect(archs).To(ConsistOf(utils.ArchitecturePpc64le),
				"CEL rule matching generateName should apply ppc64le")
		})
	})

	Context("Plugin Disabled", func() {

		It("should not modify pod affinity or nodeSelector when the CEL plugin is disabled (Enabled: false)", func() {
			ctx := context.Background()
			recorder := record.NewFakeRecorder(8)

			original := NewPod().
				WithName("test-pod").
				WithNamespace("default").
				WithContainersImages("nginx:latest").
				Build()

			ppcs := []v1beta1.PodPlacementConfig{
				*NewPodPlacementConfig().
					WithName("disabled-cel-ppc").
					WithNamespace("default").
					WithPriority(100).
					WithCelArchitecturePlacement(false, []string{utils.ArchitecturePpc64le},
						[]plugins.ArchitectureRule{
							{Name: "always-true", Expression: `true`, Architectures: []string{utils.ArchitecturePpc64le}},
						}).
					Build(),
			}

			wh := &PodSchedulingGateMutatingWebHook{}
			pod := newPod(original, ctx, recorder)
			wh.applyCELInWebhook(ctx, pod, ppcs)

			Expect(pod.Spec.Affinity).To(BeNil(),
				"expected pod.Spec.Affinity to be nil when CEL plugin is disabled")
			if pod.Spec.NodeSelector != nil {
				Expect(pod.Spec.NodeSelector).NotTo(HaveKey(utils.ArchLabel),
					"expected no arch nodeSelector when CEL plugin is disabled")
			}
		})

		It("should not touch existing pod affinity when the CEL plugin is disabled", func() {
			ctx := context.Background()
			recorder := record.NewFakeRecorder(8)

			existingTerm := corev1.NodeSelectorTerm{
				MatchExpressions: []corev1.NodeSelectorRequirement{
					{Key: "topology.kubernetes.io/zone", Operator: corev1.NodeSelectorOpIn, Values: []string{"us-east-1a"}},
				},
			}

			original := NewPod().WithName("pod-with-affinity").WithNamespace("default").
				WithAffinity(&corev1.Affinity{
					NodeAffinity: &corev1.NodeAffinity{
						RequiredDuringSchedulingIgnoredDuringExecution: &corev1.NodeSelector{
							NodeSelectorTerms: []corev1.NodeSelectorTerm{existingTerm},
						},
					},
				}).Build()

			ppcs := []v1beta1.PodPlacementConfig{
				*NewPodPlacementConfig().
					WithName("disabled-ppc").
					WithNamespace("default").
					WithCelArchitecturePlacement(false, []string{utils.ArchitecturePpc64le}, nil).
					Build(),
			}

			wh := &PodSchedulingGateMutatingWebHook{}
			pod := newPod(original, ctx, recorder)
			wh.applyCELInWebhook(ctx, pod, ppcs)

			Expect(pod.Spec.Affinity).NotTo(BeNil(),
				"pod affinity should not have been removed by a disabled CEL plugin")
			Expect(pod.Spec.Affinity.NodeAffinity).NotTo(BeNil())
			Expect(pod.Spec.Affinity.NodeAffinity.RequiredDuringSchedulingIgnoredDuringExecution).NotTo(BeNil())
			terms := pod.Spec.Affinity.NodeAffinity.RequiredDuringSchedulingIgnoredDuringExecution.NodeSelectorTerms
			Expect(terms).To(HaveLen(1))
			Expect(terms[0].MatchExpressions).To(HaveLen(1))
			Expect(terms[0].MatchExpressions[0].Key).To(Equal("topology.kubernetes.io/zone"),
				"existing affinity term was modified by disabled plugin")
		})
	})

	Context("Scheduling Gate Idempotency", func() {

		It("should not add a duplicate scheduling gate when it is already present", func() {
			ctx := context.Background()
			recorder := record.NewFakeRecorder(8)

			raw := NewPod().
				WithName("pre-gated").
				WithNamespace("default").
				WithSchedulingGates(utils.SchedulingGateName).
				Build()
			pod := newPod(raw, ctx, recorder)
			pod.ensureSchedulingGate()

			count := 0
			for _, g := range pod.Spec.SchedulingGates {
				if g.Name == utils.SchedulingGateName {
					count++
				}
			}
			Expect(count).To(Equal(1),
				"expected exactly 1 instance of scheduling gate %q, got %d — gates=%v",
				utils.SchedulingGateName, count, pod.Spec.SchedulingGates)
		})

		It("should add the scheduling gate when the pod does not have it", func() {
			ctx := context.Background()
			recorder := record.NewFakeRecorder(8)

			raw := NewPod().
				WithName("ungated").
				WithNamespace("default").
				Build()
			pod := newPod(raw, ctx, recorder)
			pod.ensureSchedulingGate()

			found := false
			for _, g := range pod.Spec.SchedulingGates {
				if g.Name == utils.SchedulingGateName {
					found = true
				}
			}
			Expect(found).To(BeTrue(),
				"expected scheduling gate %q to be added, got gates=%v",
				utils.SchedulingGateName, pod.Spec.SchedulingGates)
		})

		It("should preserve pre-existing gates from other controllers when adding the MTO gate", func() {
			ctx := context.Background()
			recorder := record.NewFakeRecorder(8)

			raw := NewPod().
				WithName("multi-gated").
				WithNamespace("default").
				WithSchedulingGates("other-controller.example.com/my-gate").
				Build()
			pod := newPod(raw, ctx, recorder)
			pod.ensureSchedulingGate()

			Expect(pod.Spec.SchedulingGates).To(HaveLen(2),
				"expected at least 2 gates after ensureSchedulingGate")

			mtoGateFound := false
			otherGateFound := false
			for _, g := range pod.Spec.SchedulingGates {
				switch g.Name {
				case utils.SchedulingGateName:
					mtoGateFound = true
				case "other-controller.example.com/my-gate":
					otherGateFound = true
				}
			}
			Expect(mtoGateFound).To(BeTrue(),
				"MTO gate not found after ensureSchedulingGate; gates=%v", pod.Spec.SchedulingGates)
			Expect(otherGateFound).To(BeTrue(),
				"pre-existing gate was removed by ensureSchedulingGate; gates=%v", pod.Spec.SchedulingGates)
		})

		It("should still add the scheduling gate even when the CEL plugin is disabled", func() {
			ctx := context.Background()
			recorder := record.NewFakeRecorder(8)

			raw := NewPod().
				WithName("disabled-gate-test").
				WithNamespace("default").
				WithContainersImages("nginx:latest").
				Build()
			pod := newPod(raw, ctx, recorder)

			ppcs := []v1beta1.PodPlacementConfig{
				*NewPodPlacementConfig().
					WithName("disabled-ppc").
					WithNamespace("default").
					WithCelArchitecturePlacement(false, []string{utils.ArchitecturePpc64le}, nil).
					Build(),
			}

			wh := &PodSchedulingGateMutatingWebHook{}
			wh.applyCELInWebhook(ctx, pod, ppcs)

			Expect(pod.Spec.Affinity).To(BeNil(),
				"disabled CEL plugin must not set affinity; got: %+v", pod.Spec.Affinity)

			pod.ensureSchedulingGate()
			Expect(pod.HasSchedulingGate()).To(BeTrue(),
				"scheduling gate should be present even when CEL plugin is disabled")
		})
	})

	Context("Concurrent Admission Safety", func() {
		It("should handle concurrent applyCELInWebhook calls without data races", func() {
			ctx := context.Background()

			ppcs := []v1beta1.PodPlacementConfig{
				*NewPodPlacementConfig().
					WithName("concurrent-ppc").
					WithNamespace("default").
					WithPriority(100).
					WithCelArchitecturePlacement(true, []string{utils.ArchitectureAmd64},
						[]plugins.ArchitectureRule{
							NewRule("match-all", "true", utils.ArchitecturePpc64le),
						}).
					Build(),
			}

			wh := &PodSchedulingGateMutatingWebHook{}

			const goroutines = 20
			var wg sync.WaitGroup
			wg.Add(goroutines)
			for i := 0; i < goroutines; i++ {
				go func(idx int) {
					defer wg.Done()
					defer GinkgoRecover()
					recorder := record.NewFakeRecorder(8)
					pod := NewPod().
						WithName(fmt.Sprintf("concurrent-pod-%d", idx)).
						WithNamespace("default").Build()
					wrappedPod := newPod(pod, ctx, recorder)
					wh.applyCELInWebhook(ctx, wrappedPod, ppcs)
					archs := extractArchitectures(pod)
					Expect(archs).To(ConsistOf(utils.ArchitecturePpc64le))
				}(i)
			}
			wg.Wait()
		})
	})
})
