## Append samples you want in your CSV to this file as resources ##
resources:
- v1beta1_clusterpodplacementconfig.yaml
- v1alpha1_clusterpodplacementconfig.yaml
- v1beta1_podplacementconfig.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
