## Append samples you want in your CSV to this file as resources ##
resources:
- multiarch_v1beta1_nodeaffinityscoring_clusterpodplacementconfig.yaml

#+kubebuilder:scaffold:manifestskustomizesamples
