apiVersion: multiarch.openshift.io/v1beta1
kind: ClusterPodPlacementConfig
metadata:
  name: cluster
spec:
  logVerbosity: Normal
  namespaceSelector:
    matchExpressions:
    - key: multiarch.openshift.io/exclude-pod-placement
      operator: DoesNotExist
  plugins:
    nodeAffinityScoring:
      enabled: true
      platforms:
      - architecture: amd64
        # os: linux
        weight: 100
