kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ../../core/namespaces/openshift-multiarch-tuning-operator
  - ../../config.openshift.io/imagedistedmirrorsets/multiarch-tuning-operator-fbc-staging
  - ../../operators.coreos.com/catalogsources/multiarch-tuning-operator-catalog
  - ../../operators.coreos.com/operatorgroups/openshift-multiarch-tuning-operator
  - ../../operators.coreos.com/subscriptions/openshift-multiarch-tuning-operator

patches:
  - target:
      group: operators.coreos.com
      version: v1alpha1
      kind: CatalogSource
      name: multiarch-tuning-operator-catalog
    patch: |-
      - op: replace
        path: /spec/image
        value: quay.io/multi-arch/multiarch-tuning-operator:catalog
